# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/turtle_command.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/turtle_command.proto',
  package='turtlesim_controller',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aproto/turtle_command.proto\x12\x14turtlesim_controller\"\xaa\x01\n\rTurtleCommand\x12=\n\x04type\x18\x01 \x01(\x0e\x32/.turtlesim_controller.TurtleCommand.CommandType\x12\r\n\x05value\x18\x02 \x01(\x02\x12\r\n\x05speed\x18\x03 \x01(\x02\"<\n\x0b\x43ommandType\x12\x08\n\x04STOP\x10\x00\x12\x0b\n\x07\x46ORWARD\x10\x01\x12\x0c\n\x08\x42\x41\x43KWARD\x10\x02\x12\x08\n\x04TURN\x10\x03\x62\x06proto3'
)



_TURTLECOMMAND_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='turtlesim_controller.TurtleCommand.CommandType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FORWARD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BACKWARD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TURN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=163,
  serialized_end=223,
)
_sym_db.RegisterEnumDescriptor(_TURTLECOMMAND_COMMANDTYPE)


_TURTLECOMMAND = _descriptor.Descriptor(
  name='TurtleCommand',
  full_name='turtlesim_controller.TurtleCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='turtlesim_controller.TurtleCommand.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='turtlesim_controller.TurtleCommand.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='turtlesim_controller.TurtleCommand.speed', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TURTLECOMMAND_COMMANDTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=223,
)

_TURTLECOMMAND.fields_by_name['type'].enum_type = _TURTLECOMMAND_COMMANDTYPE
_TURTLECOMMAND_COMMANDTYPE.containing_type = _TURTLECOMMAND
DESCRIPTOR.message_types_by_name['TurtleCommand'] = _TURTLECOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TurtleCommand = _reflection.GeneratedProtocolMessageType('TurtleCommand', (_message.Message,), {
  'DESCRIPTOR' : _TURTLECOMMAND,
  '__module__' : 'proto.turtle_command_pb2'
  # @@protoc_insertion_point(class_scope:turtlesim_controller.TurtleCommand)
  })
_sym_db.RegisterMessage(TurtleCommand)


# @@protoc_insertion_point(module_scope)
